### ISSUE TITLE
Make Crouton Screen Reader-friendly

### ISSUE THREAD

**Issue by prbrian** [bmlt-enabled/crouton#335] opened 2021-06-29 23:38 UTC
**Is your feature request related to a problem? Please describe.**
A screen reader used by someone who is blind or visually-impaired does not adequately read the crouton. 

**Describe the solution you'd like**
Could crouton be made screen reader-friendly?

**Comment by pjaudiomv** [comment] 2021-06-30 00:00
Duplicate of https://github.com/bmlt-enabled/crouton/issues/178

**Comment by prbrian** [comment] 2021-06-30 00:51
Thank you. My apologies

Brian S.
Public Relations Representative
Fellowship Development Team
Ontario Region and Manitoba Area of Narcotics Anonymous
Cell: (289) 668-6974
Toll-free: 1-888-811-3887
Email: ***@***.***
Website: www.orscna.org

**Closed** 2021-07-11 23:44 UTC
Labels: enhancement
