### ISSUE TITLE
Display not in Chronological order again

### ISSUE THREAD

**Issue by EddieW1** [bmlt-enabled/crouton#290] opened 2020-10-03 00:20 UTC
**Describe the bug**

Meeting info for Oahu is not showing in Chronological order. This issue is only happening on Friday all other days are functioning correctly.

**To Reproduce**
1. Go to 'Na-Hawaii.org'
2. Click on 'Meeting Schedules.'
3. Scroll down to 'Oahu Schedule for Friday'

**Expected behavior**

Meeting should display in chronological order

**Screenshots**

<img width="829" alt="Screen Shot 2020-10-02 at 2 11 22 PM" src="https://user-images.githubusercontent.com/50605252/94978600-d392b480-04b9-11eb-97dc-9d7b379f4c9c.png">

**Desktop (please complete the following information):**
 - OS: [MacOS 10.14.6]
 - Browser [Firefox, chrome, safari]
 - Version [Safari 14.0, Chrome 85.0.4183.121, Firefox 81.0.1]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by jbraswell** [comment] 2020-10-03 04:13
Duplicate of https://github.com/bmlt-enabled/crouton/issues/289. Closing this, but we will get it fixed.

**Closed** 2020-10-03 04:13 UTC
Labels: bug

**Comment by jbraswell** [comment] 2020-10-03 04:38
@EddieW1 I am releasing 3.11.7 right now. When it's available, please upgrade, let us know how it goes.
