### ISSUE TITLE
Strange Bug That *MAY* Be Crouton

### ISSUE THREAD

**Issue by LittleGreenViper** [bmlt-enabled/crouton#81] opened 2019-01-05 19:26 UTC
This happens on the GNYR Server. I haven't tested it on others.

We are running the latest WP, PHP 7.2.10, latest MySQL (I think 5.6.X). Latest Crouton, pointing to the GNYR Root Server: https://bmlt.newyorkna.org/main_server/

WAY too many plugins. It's sick. I'm embarrassed.

In any case on this page. I entered ONLY this code (the display is as a block, but this happens without the wrappers, where the only code on the page is the shortcode): https://newyorkna.org/meetings/tabbed-searches/long-island-tabbed-search/

Here is the entire page code:

[bmlt_tabs service_body="1001,1002,1003,1004,1067"]

If you see the attached image, I'm told that "updating failed" each time I hit the "UPDATE" button, and I'm told I have a newer autosave the next time I go into that page, but the code in the page is actually up to date (if you can see "Choose Your Weapon" on Saturday morning, then the new code is effective).

![screengrab 2019-01-05 at 2 20 14 pm](https://user-images.githubusercontent.com/29312814/50728311-c20a5600-10f5-11e9-863c-0fff91cf17e0.png)

**Comment by LittleGreenViper** [comment] 2019-01-05 21:42
Yes (see the comments around it? They don't show up in the original bug report).

However, this did begin life as a standalone shortcode. I deleted it, and re-added it as a shortcode block (and got the same error). I wonder if it's because the original was in the history?

**Comment by LittleGreenViper** [comment] 2019-01-05 21:45
![screengrab 2019-01-05 at 4 44 26 pm](https://user-images.githubusercontent.com/29312814/50729508-37335680-1109-11e9-88cb-9dec7c950ad1.png)
That's a nope. I even restored an autosave that had the block.

I am NOT thrilled with Gutenberg.

**Comment by LittleGreenViper** [comment] 2019-01-05 21:45
Like I said, it works. It seems the editor gets its panties in a twist.

**Comment by californiasteve** [comment] 2019-01-05 21:48
I'm with you on Gutenberg, if it was a new install it works fine but any upgrade to it sucks. Good luck Chris.

**Comment by LittleGreenViper** [comment] 2019-01-05 21:57
Probably has to do with the autosaves, then.

**Comment by radius314** [comment] 2019-03-21 21:42
root cause: a shortcode should only return data, not render it.  there was some legacy code that was inserting a div in the shortcode method `tabbedUI`.  

here's the issue that helped fix it https://github.com/WordPress/gutenberg/issues/3576

**Comment by radius314** [comment] 2019-03-21 21:53
will be fixed in crouton 2.5.0

**Closed by radius314** 2019-03-21 21:53 UTC
