### ISSUE TITLE
exclude zip codes not working with multiple zip codes

### ISSUE THREAD

**Issue by pjaudiomv** [bmlt-enabled/crouton#99] opened 2019-04-29 14:10 UTC
when using exclude zip code option, one zip code works fine. When trying to use multiple zips separated by comma I get the following js error.

![Screen Shot 2019-04-29 at 9 44 37 AM](https://user-images.githubusercontent.com/34245618/56901848-0b94fd00-6a67-11e9-8c73-c82e0b830fed.png)

**Comment by radius314** [comment] 2019-04-29 21:35
I could not reproduce this issue.

**Comment by pjaudiomv** [comment] 2019-04-29 22:03
just uploaded video on slack reproducing problem, on latest build

**Comment by radius314** [comment] 2019-04-29 22:28
fix is in master

**Comment by pjaudiomv** [comment] 2019-04-29 22:33
👍

**Comment by radius314** [comment] 2019-04-29 22:33
does that mean passed testing?

**Comment by pjaudiomv** [comment] 2019-04-30 12:43
Yes it passed

**Closed** 2019-04-30 15:51 UTC
Labels: 2.6.0, bug
