### ISSUE TITLE
Wordpress EventOn plugin has conflict

### ISSUE THREAD

**Issue by californiasteve** [bmlt-enabled/crouton#217] opened 2020-03-24 00:09 UTC
When the EventOn plugin is activated Crouton does not render on the page. 
WP 5.3.2 using Italian language
EventOn 2.8.5
Crouton 3.8.8

**Comment by pjaudiomv** [comment] 2020-03-24 00:11
yes bruce had same issue, this is caused by moment js loading twice.

**Comment by pjaudiomv** [comment] 2020-03-24 00:11
if you comment out line 81 of `wp-content/plugins/eventon/includes/class-frontend.php`

`//wp_register_script('evo_moment',plugins_url(EVENTON_BASE) . '/assets/js/lib/moment.min.js', array('jquery'), EVO()->version, true ); // 2.8`

this will fix it.

**Comment by pjaudiomv** [comment] 2020-03-24 00:13
unfortunately theres not a great way to deal with this. one because of the way crouton loads javascript and two because moment is not built in to wordpress its hard to detect it and load safely. Danny may have better ideas, but I could not find any.

**Comment by californiasteve** [comment] 2020-03-24 00:16
Yup, until EventOn updates then it will break again. Danny said to open a ticket so here it is, lol.

**Comment by radius314** [comment] 2020-03-25 22:02
@californiasteve can you share a link to the eventon plugin you are using?

**Comment by californiasteve** [comment] 2020-03-25 22:22
Paid version https://www.myeventon.com/

**Comment by brustar64** [comment] 2020-04-01 13:14
This has moved to line 82 in ver 2.8.7

![image](https://user-images.githubusercontent.com/29008815/78141223-84b68480-746e-11ea-9d26-e1e53a56cdae.png)

**Comment by radius314** [comment] 2020-04-05 16:35
Does anyone recall what the exact error is?

**Comment by radius314** [comment] 2020-04-06 20:50
Moving date-fns would like have a dependency on migrating crouton to use webpack instead of gulp.  https://github.com/bmlt-enabled/crouton/issues/207

**Comment by brustar64** [comment] 2020-04-10 15:01
It doesn't display render anything when you are trying to user croutonjs to display Virtual-na in your web page.
________________________________

**Comment by californiasteve** [comment] 2020-05-25 16:21
In newest version this is found on line #173

**Comment by radius314** [comment] 2020-05-25 16:41
I had looked into this, it’s a pretty major rewrite of some of timezone
logic to not use momentjs.  Not really worth the effort for a small subset
of users.

**Comment by ashanjay** [comment] 2020-07-28 17:38
Hey guys, thanks for raising this issue and bringing awareness to it. We recently started loading moment.js into eventON. I am not really sure why loading of the library again into the site would cause issues. We will however add option in eventON in the future to disable moment.js from loading if it already exists, until a no-conflict solution can be implemented. 

Best Regards! Stay safe!

**Comment by californiasteve** [comment] 2020-11-03 00:36
Newest release 3.0.2 has a setting to not load moment. It's in the myeventOn - Scripts & Styling at the bottom.

**Comment by pjaudiomv** [comment] 2020-11-03 00:46
awesome :)

**Comment by radius314** [comment] 2020-11-14 03:11
Fair to close this out then?

**Closed** 2020-11-14 03:18 UTC
Labels: bug
